### ISSUE TITLE
Release Studio as an opensource sample

### ISSUE THREAD

**Issue by AlexanderLunde** [AI-Empower-Labs/Studio#2]
Today Studio is a part of the standard containers
It would be better to release studio as an open source sample application on top of our APIs

Benefits:
* Reduce the expectations on the studio UI form customer when doing demos
* Short customers own implementation time with the available source code for the studio app
* Make is simples for us to involve a low cost help to improve the UX/UI in the future, not needing to give them access to the valuable part of our software

**Comment by Esben-Carlsen** [comment]
OBsoleted by https://github.com/AI-Empower-Labs/Studio/issues/5
