### ISSUE TITLE
Option to choose from black or white screen in AEL Studio.

### ISSUE THREAD

**Issue by jerkervannerus** [AI-Empower-Labs/Studio#4]
Option to choose from black or white screen in AEL Studio. Or at least in white. Very hard to see now when doing demos.

**Comment by Esben-Carlsen** [comment]
Added options to switch to and from dark / light theme

Default theme is detected from operating system settings.
Theme is changed using a icon button in the upper right corner

@jerkervannerus Please validate this works as you expect.

**Comment by jerkervannerus** [comment]
Great work!
